# This .travis.yml on:
# https://github.com/loot/loot/blob/dev/.travis.yml
# https://genbattle.bitbucket.io/blog/2016/01/17/c++-travis-ci/?

language: cpp
dist: trusty

env:
  global:
    #- MAKEFLAGS="-j 2"

cache:
  directories:
    - $HOME/.ccache
    - $HOME/deps

addons:
  apt:
    sources: &default_sources
      - ubuntu-toolchain-r-test
    packages: &default_packages
      # - libhdf5-dev

matrix:
  include:

    - os: linux
      compiler: gcc
      env: CXX_COMPILER_NAME='g++-6' CXX_COMPILER_ID=GNU
      addons: {apt: { packages: [*default_packages, g++-6], sources: [*default_sources]}}

    - os: linux
      compiler: gcc
      env: CXX_COMPILER_NAME='g++-7' CXX_COMPILER_ID=GNU
      addons: {apt: { packages: [*default_packages, g++-7], sources: [*default_sources]}}

    - os: linux
      compiler: clang
      env: CXX_COMPILER_NAME='clang++-6.0' CXX_COMPILER_ID=LLVM
      addons: {apt: { packages: [*default_packages, clang-6.0], sources: [*default_sources, llvm-toolchain-trusty-6.0]}}

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env: CXX_COMPILER_NAME='c++' CXX_COMPILER_ID=APPLE

    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env: CXX_COMPILER_NAME='c++' CXX_COMPILER_ID=APPLE

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env: CXX_COMPILER_NAME='clang++' CXX_COMPILER_ID=LLVM

before_install:
  # Check commit matches expected commit (because of Travis bug)
  - if [[ "$TRAVIS_COMMIT" != "$(git rev-parse HEAD)" ]]; then echo "Commit doesn't match expected $TRAVIS_COMMIT"; fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$CXX_COMPILER_ID" == "LLVM" ]]; then
      brew install --with-clang llvm@6
      brew link --force --overwrite llvm@6
    fi
  # This is required to override Travis's definitions of CC and CXX that lead to old Ubuntu-packaged compilers
  - export CXX="$CXX_COMPILER_NAME"

install:
    #--------- Linux
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      SWIGHOME=$HOME/deps/swig_3.0.12
      if [[ -z "$(ls -A $SWIGHOME)" ]]; then
        cd /tmp/;
        curl -s -J -O -k -L 'https://sourceforge.net/projects/swig/files/swig/swig-3.0.12/swig-3.0.12.tar.gz/download'
        tar xf swig-3.0.12.tar.gz > /dev/null 2>&1
        cd swig-3.0.12 && ./configure --prefix $SWIGHOME
        make && make install
        cd $TRAVIS_BUILD_DIR
      else
        echo "Already have swig cache"
      fi
      export CMAKE_PREFIX_PATH=$SWIGHOME:$CMAKE_PREFIX_PATH
    fi
    #--------- OSX
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew upgrade python cmake
      brew install ccache swig
    fi
    #--------- All platforms
  - |
    export BOOSTHOME=$HOME/deps/boost_1_66_0
    if [[ -z "$(ls -A $BOOSTHOME)" ]]; then
      cd /tmp/
      wget -O boost_1_66_0.tar.gz https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.gz -q
      tar xf boost_1_66_0.tar.gz > /dev/null 2>&1
      cd boost_1_66_0/
      # Configure & build  --prefix: install dir for boost  --with-libraries: only build libraries that we actually need
      ./bootstrap.sh --prefix=$BOOSTHOME --with-libraries=chrono,date_time,filesystem,iostreams,locale,regex,system,thread
      ./b2 -q -a -j2 -d0 --disable-filesystem2 cxxflags="-v -std=c++11" threading=multi install
      cd $TRAVIS_BUILD_DIR;
    else
      echo "Already have boost cache"
    fi
    export LD_LIBRARY_PATH=$BOOSTHOME/lib:$LD_LIBRARY_PATH
    sudo rm -f /usr/local/lib/libboost*.dylib*
    sudo ln -s $BOOSTHOME/lib/*.{so,dylib}* /usr/local/lib

script:
  # Build stride and run tests
  #			STRIDE_BOOST_ROOT: specify where the correct version of boost can be found
  #			STRIDE_BOOST_NO_SYSTEM_PATHS: should be ON to prevent mixing different versions of boost
  # Arbitrarily chosen one platform for Debug build.
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$CXX_COMPILER_ID" == "LLVM" ]]; then
      CMAKE_BUILD_TYPE=Debug STRIDE_BOOST_ROOT=$BOOSTHOME STRIDE_BOOST_NO_SYSTEM_PATHS=ON make all
      CMAKE_BUILD_TYPE=Debug make test
    else
      STRIDE_BOOST_ROOT=$BOOSTHOME STRIDE_BOOST_NO_SYSTEM_PATHS=ON make all
      make test
    fi
