# This is a sample build configuration for C++ â€“ Make.
# Only use spaces to indent your .yml configuration.
# -----
# You can use any Docker image from Docker Hub, or your own container registry, as your build environment.
#image: gcc:6.1
image: ubuntu
pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - make all
          - make test

